<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KLU9IMMS" failures="2" tests="3" name="Error Validation Test" time="51.087" errors="0" timestamp="7 Feb 2024 16:11:11 GMT">
  <testcase classname="vinayakshettypractice.tests.ErrorValidationsTest" name="LoginErrorValidation" time="1.095"/>
  <testcase classname="vinayakshettypractice.tests.ErrorValidationsTest" name="ProductErrorValidation" time="13.435">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at vinayakshettypractice.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
  <testcase classname="vinayakshettypractice.tests.ErrorValidationsTest" name="ProductErrorValidation" time="23.41">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at vinayakshettypractice.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:55)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validation Test -->
